apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: # labels of the replicaset object itself
    app: myapp
    function: front-end
  annotations:
    buildVersion: "1.34"
spec:
  replicas: 3

  # in order to connect the replicaset to the pods, we use selector field to match the labels defined on the pods. A single label match
  # will do the work of selecting the pods. However, if you feel there could be other pods with the same label but with a different function,
  # then you could get more exact and specify other labels when selecting the pods(using selector) to ensure that the right pods are
  # discovered(selected) by the replicaset.
  selector:
    matchLabels:
      type: front-end

  template:
    # We put the pod-definition lines here to define the pod template
    metadata:
      name: nginx
      labels: # labels of the pods. These are used to discover the pods by the replicaset or other objects.
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
