apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: data-processor
      image: data-processor

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  # Place the pod on any node with key of size and values of Large or Medium
                  - Large
                  - Medium

                # or:
#                key: size
#                operator: NotIn
#                values:
#                  - Small

                # or as long as we're sure we don't set a label `size` to the smaller nodes, using the Exist operator will give us the same result
                # in this case. The Exist operator will check if the specified label(in the `key`) exists on the nodes and you don't need the
                # values section for that, as it doesn't compare the values.
#                key: size
#                operator: Exists
