apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80 # the port where the set of pods are exposed
      port: 80 # where the service is exposed
  selector: # to link the service to a set of pods, use selector. Use the `labels` section of pods to select them.
    app: myapp
    type: front-end
