apiVersion: v1
kind: Pod
metadata:
  name: nginx # pod name
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx # name of the container within the pod
      image: nginx # image name in the docker repository. If you're using other registries than docker hub, specify the full path to that image repository.

      # we can add additional containers to the pod
#    - name: busybox
#      image: busybox