apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: nginx-container
      image: nginx

  tolerations: # all of the values need to be in double quotes
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"