apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  # It can have labels, but we don't need that for now
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector: # This links the service to the pod.
    app: myapp
    type: front-end
